 
version: '3'

services: 
  backend:
    build:
      context: .
      dockerfile: ./compose/backend/Dockerfile
    image: devansh2290/h1-growth-framework-backend
    env_file: 
      - ./.envs/.production/.backend
      - ./.envs/.production/.database
    volumes:
      - ./backend:/app
    command: /start

  nginx:
    build: 
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    image: devansh2290/h1-growth-framework-nginx
    depends_on:
      - backend
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/conf.d/nginx.production.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/app
    ports:
      - "80:80"
      - "81:81"
    env_file: 
      - ./.envs/.production/.nginx
    command: ["nginx", "-g", "daemon off;"]