 
version: '3'

volumes:
  database_mysql_data: {}

services: 
  database:
    build:
      context: .
      dockerfile: ./compose/database/Dockerfile
    image: awesome_project_local_database
    env_file:
      - ./.envs/.local/.database
    volumes:
      - database_mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: ./compose/backend/Dockerfile
      args:
        - BUILD_ENV=local
    image: awesome_project_local_backend
    depends_on: 
      - database
    env_file: 
      - ./.envs/.local/.backend
      - ./.envs/.local/.database
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: /start

  frontend:
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile
    image: awesome_project_local_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    command: /start

  nginx:
    build: 
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    image: h1_demo_prod_nginx
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/conf.d/nginx.local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    env_file: 
      - ./.envs/.local/.nginx
    command: ["nginx", "-g", "daemon off;"]