 
version: '3'

volumes:
  database_mysql_data: {}

services: 
  database:
    build:
      context: .
      dockerfile: ./compose/database/Dockerfile
    image: devansh2290/h1-growth-framework-database
    env_file:
      - ./.envs/.production/.database
    volumes:
      - database_mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: ./compose/backend/Dockerfile
    image: devansh2290/h1-growth-framework-backend
    depends_on: 
      - database
    env_file: 
      - ./.envs/.production/.backend
      - ./.envs/.production/.database
    volumes:
      - ./backend:/app
    ports: 
      - 8000:8000
    command: /start

  nginx:
    build: 
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    image: devansh2290/h1-growth-framework-nginx
    depends_on:
      - backend
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/conf.d/nginx.production.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "81:81"
    env_file: 
      - ./.envs/.production/.nginx
    command: ["nginx", "-g", "daemon off;"]