#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


if [ -z "${MYSQL_USER}" ]; then
    base_mysql_image_default_user='postgres'
    export MYSQL_USER="${base_mysql_image_default_user}"
fi
export DATABASE_URL="mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}"

mysql_ready() {
python << END
import sys
import MySQLdb
try:
    MySQLdb._mysql.connect(
        db="${MYSQL_DATABASE}",
        user="${MYSQL_USER}",
        passwd="${MYSQL_PASSWORD}",
        host="${MYSQL_HOST}",
        port=${MYSQL_PORT},
    )
except MySQLdb._exceptions.OperationalError as e:
    print(e)
    sys.exit(-1)
sys.exit(0)
END
}
until mysql_ready; do
  >&2 echo 'Waiting for MySQL to become available...'
  sleep 1
done
>&2 echo 'MySQL is available'

exec "$@"